apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorers-helidon
  labels:
    app: explorers-mp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: explorers-mp
  template:
    metadata:
      labels:
        app: explorers-mp
    spec:
      containers:
        - name: explorers-helidon
          image: localhost:5000/nino/explorers-helidon:v1
          imagePullPolicy: Never # needed for local images
          ports:
            - containerPort: 8080
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: explorers-helidon
#  labels:
#    app: explorers-helidon
#spec:
#  type: NodePort
#  selector:
#    app: explorers-helidon
#  ports:
#  - port: 8080
#    targetPort: 8080
#    name: http