apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorers-helidon
  labels:
    app: explorers-mp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: explorers-mp
  template:
    metadata:
      labels:
        app: explorers-mp
    spec:
      containers:
        - name: explorers-helidon
          image: localhost:5000/nino/distroless-explorers-helidon:0.2
          imagePullPolicy: Never # needed for local images
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: explorers-helidon
spec:
  type: NodePort
  selector:
    app: explorers-mp
  ports:
      - port: 8081 # port of the service in the cluster
        targetPort: 8080 # port of the application in the container
        nodePort: 30000 # port of the service outside the cluster